### ISSUE TITLE
Failure if --target not given

### ISSUE THREAD

**Issue by iainrb** [oicr-gsi/bam-qc-metrics#12]
Analysis crashes if the `--target` option is not specified, as follows:

`(bamqc) ibancarz@ld5312-ibanca:~/playground/bamqc_test_data/20180816/A00469_0047/test$ run_bam_qc.py -b ../../../SWID_14343630_TGL41_0004_nn_R_PE_320_CM_HMC_4_190531_M00146_0054_000000000-D6CW8_GTTACGCA-ATCGCCAT_L001_001.annotated.bam -o  test.json
Traceback (most recent call last):
  File "/home/ibancarz/playground/bam-qc-metrics-v0.1.6/bin/run_bam_qc.py", line 138, in <module>
    main()
  File "/home/ibancarz/playground/bam-qc-metrics-v0.1.6/bin/run_bam_qc.py", line 134, in main
    qc = bam_qc(config)
  File "/home/ibancarz/playground/bam-qc-metrics-v0.1.6/bam_qc_metrics/bam_qc.py", line 122, in __init__
    fast_finder.read_length_summary())
  File "/home/ibancarz/playground/bam-qc-metrics-v0.1.6/bam_qc_metrics/bam_qc.py", line 625, in __init__
    self.metrics = self.evaluate_all_metrics()
  File "/home/ibancarz/playground/bam-qc-metrics-v0.1.6/bam_qc_metrics/bam_qc.py", line 630, in evaluate_all_metrics
    self.evaluate_bedtools_metrics(),
  File "/home/ibancarz/playground/bam-qc-metrics-v0.1.6/bam_qc_metrics/bam_qc.py", line 642, in evaluate_bedtools_metrics
    metrics['number of targets'] = targetBedTool.count()
  File "/home/ibancarz/playground/bam-qc-metrics-v0.1.6/pybedtools/bedtool.py", line 2507, in count
    return sum(1 for _ in iter(self))
  File "/home/ibancarz/playground/bam-qc-metrics-v0.1.6/pybedtools/bedtool.py", line 2507, in <genexpr>
    return sum(1 for _ in iter(self))
  File "pybedtools/cbedtools.pyx", line 754, in pybedtools.cbedtools.IntervalIterator.__next__
TypeError: NoneType object is not an iterator
`

**Comment by iainrb** [comment]
Resolved by https://github.com/oicr-gsi/bam-qc-metrics/pull/14
